apiVersion: v1
kind: Service
metadata:
  name: gamebot
  labels:
    name: gamebot    
spec:
  selector:
    name: gamebot    
  type: LoadBalancer
  ports:
   - port: 80
     name: gamebot
     targetPort: 8080
     protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamebot
spec:
  replicas: 2
  selector:
    matchLabels:
      name: gamebot      
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: gamebot        
    spec:
      imagePullSecrets:
      - name: team10acr63c858
      containers:
      - name: gamebot
        image: team10acr63c858.azurecr.io/gamebot:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: gamebot         
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        env: 
          - name: "PORT"
            value: "8080"
          - name: "PICK_STRATEGY"
            value: "RANDOM"
          - name: "FF_BETS"
            value: "true"
          - name: "APPINSIGHTS_INSTRUMENTATIONKEY"
            value: "2e9f6c29-0409-4576-9d0e-cb15a60148b5"
